-- MySQL Script generated by MySQL Workbench
-- 04/24/14 19:27:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_auditoria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_auditoria` ;
CREATE SCHEMA IF NOT EXISTS `db_auditoria` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_auditoria` ;

-- -----------------------------------------------------
-- Table `db_auditoria`.`cajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_auditoria`.`cajero` ;

CREATE TABLE IF NOT EXISTS `db_auditoria`.`cajero` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auditoria`.`tipo_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_auditoria`.`tipo_operacion` ;

CREATE TABLE IF NOT EXISTS `db_auditoria`.`tipo_operacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auditoria`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_auditoria`.`auditoria` ;

CREATE TABLE IF NOT EXISTS `db_auditoria`.`auditoria` (
  `id` INT NOT NULL,
  `cajero` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `ciudadano` VARCHAR(45) NULL,
  `monto_anterior` DECIMAL(10,2) NULL,
  `monto_saldo` DECIMAL(10,2) NULL,
  `ip` VARCHAR(45) NULL,
  `mac` VARCHAR(45) NULL,
  `nombre_maquina` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `tipo_operacion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_operacion_id`),
  INDEX `fk_auditoria_tipo_operacion1_idx` (`tipo_operacion_id` ASC),
  CONSTRAINT `fk_auditoria_tipo_operacion1`
    FOREIGN KEY (`tipo_operacion_id`)
    REFERENCES `db_auditoria`.`tipo_operacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auditoria`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_auditoria`.`pago` ;

CREATE TABLE IF NOT EXISTS `db_auditoria`.`pago` (
  `id` INT NOT NULL,
  `ciudadano` VARCHAR(45) NULL,
  `monto` DECIMAL(10,2) NULL,
  `descripcion` VARCHAR(45) NULL,
  `cajero_id` INT NOT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`, `cajero_id`),
  INDEX `fk_PAGOS_cajero_idx` (`cajero_id` ASC),
  CONSTRAINT `fk_PAGOS_cajero`
    FOREIGN KEY (`cajero_id`)
    REFERENCES `db_auditoria`.`cajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
